version: '3'

services:
  dbprojeto:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_db
      MYSQL_USER: crud_user
      MYSQL_PASSWORD: crud_password

  php:
      build: .
      ports:
        - "8080:80"
      volumes:
        - ./:/var/www/html
      restart: always

volumes:
  db_data:
